import type { ShareGptApi } from '@/types/api'

// 主进程 IPC 桥。dev 在浏览器(无 preload)时给出空安全实现, 便于纯前端调试。
const noop = () => undefined
const fallback = {
  platform: 'web',
  setThemeSource: async () => undefined,
  loadSettings: async () => ({}),
  saveSettings: async () => undefined,
  importSettings: async () => undefined,
  loadChatHistory: async () => ({}),
  saveChatHistory: async () => undefined,
  loadCalendar: async () => ({ version: 1, calendars: [], events: [] }),
  saveCalendar: async () => undefined,
  loadTasks: async () => ({ version: 1, lists: [], tasks: [], memos: [] }),
  saveTasks: async () => undefined,
  loadFocus: async () => ({ version: 1, sessions: [], settings: null }),
  saveFocus: async () => undefined,
  vault: {
    start: async () => undefined,
    getRoot: async () => '',
    setRoot: async () => ({ ok: false, root: '', count: 0 }),
    pickFolder: async () => null,
    list: async () => [],
    readAll: async () => [],
    read: async () => ({ path: '', content: '', mtime: 0, ctime: 0 }),
    readBinary: async () => null,
    write: async () => ({ path: '', mtime: 0 }),
    create: async () => ({ path: '', content: '', mtime: 0, ctime: 0 }),
    rename: async () => ({ ok: true }),
    remove: async () => ({ ok: true }),
    importFrom: async () => ({ notes: 0, attachments: 0, skipped: 0, root: '' }),
  },
  onVaultChanged: () => noop,
  notesAi: {
    complete: async () => ({ streamId: '' }),
    cancel: async () => ({ ok: true }),
  },
  onNotesAiEvent: () => noop,
  exportUserData: async () => undefined,
  importUserData: async () => undefined,
  readClipboardAttachment: async () => undefined,
  getStatus: async () => ({}),
  getPaths: async () => ({}),
  getAppMeta: async () => ({}),
  getDeviceInfo: async () => ({}),
  getMode: async () => 'all',
  checkAppUpdate: async () => null,
  isUpdateSupported: async () => false,
  installAppUpdate: async () => ({ updated: false }),
  downloadAppUpdate: async () => undefined,
  openAppUpdate: async () => undefined,
  showSystemNotification: async () => undefined,
  openExternal: async () => undefined,
  listAiViews: async () => ({ tabs: [], activeTabId: '', activeState: null }),
  createAiView: async () => undefined,
  switchAiView: async () => undefined,
  closeAiView: async () => undefined,
  ensureAiWorkspace: async () => undefined,
  syncAiViewHost: async () => undefined,
  navigateAiWorkspace: async () => undefined,
  checkAiProxy: async () => ({ ok: false, reason: 'unavailable' }),
  executeAiJavaScript: async () => undefined,
  openProfileEditor: async () => undefined,
  emitProfileUpdated: noop,
  minimizeWindow: async () => undefined,
  toggleMaximizeWindow: async () => undefined,
  closeWindow: async () => undefined,
  isWindowMaximized: async () => false,
  isWindowFullScreen: async () => false,
  startSender: async () => undefined,
  stopSender: async () => undefined,
  startReceiver: async () => undefined,
  stopReceiver: async () => undefined,
  onLog: () => noop,
  onStatus: () => noop,
  onProfileUpdated: () => noop,
  onAiEvent: () => noop,
  onAppEvent: () => noop,
  onAppUpdateProgress: () => noop,
} as unknown as ShareGptApi

export const api: ShareGptApi = typeof window !== 'undefined' && window.api ? window.api : fallback

export const hasNativeBridge = typeof window !== 'undefined' && Boolean(window.api)
